
  CREATE TABLE "TPCH"."LINEITEM" 
   (	"ORDERKEY" NUMBER(10,0), 
	"PARTKEY" NUMBER(10,0), 
	"SUPPKEY" NUMBER(10,0), 
	"L_LINENUMBER" NUMBER(38,0), 
	"L_QUANTITY" NUMBER, 
	"L_EXTENDEDPRICE" NUMBER, 
	"L_DISCOUNT" NUMBER, 
	"L_TAX" NUMBER, 
	"L_RETURNFLAG" CHAR(1), 
	"L_LINESTATUS" CHAR(1), 
	"L_SHIPINSTRUCT" VARCHAR2(25), 
	"L_SHIPMODE" VARCHAR2(10), 
	"L_COMMENT" VARCHAR2(44)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 



  CREATE TABLE "TPCH"."ORDERS" 
   (	"ORDERKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"CUSTKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"O_ORDERSTATUS" CHAR(1) NOT NULL ENABLE, 
	"O_TOTALPRICE" NUMBER NOT NULL ENABLE, 
	"O_ORDERPRIORITY" VARCHAR2(15) NOT NULL ENABLE, 
	"O_CLERK" VARCHAR2(15) NOT NULL ENABLE, 
	"O_SHIPPRIORITY" NUMBER(*,0) NOT NULL ENABLE, 
	"O_COMMENT" VARCHAR2(79) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 



  CREATE TABLE "TPCH"."CUSTOMER" 
   (	"CUSTKEY" NUMBER(10,0), 
	"C_NAME" VARCHAR2(25), 
	"C_ADDRESS" VARCHAR2(40), 
	"NATIONKEY" NUMBER(10,0), 
	"C_PHONE" VARCHAR2(15), 
	"C_ACCTBAL" NUMBER, 
	"C_MKTSEGMENT" VARCHAR2(10), 
	"C_COMMENT" VARCHAR2(117)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 



  CREATE TABLE "TPCH"."NATION" 
   (	"NATIONKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"N_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"REGIONKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"N_COMMENT" VARCHAR2(152) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 



  CREATE TABLE "TPCH"."REGION" 
   (	"REGIONKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"R_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"R_COMMENT" VARCHAR2(152) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


