Q2_CTE_TEXT = "How can we consolidate and compare the sales data from both web and catalog sales channels by their respective sold dates and sales prices?"

Q4_CTE_TEXT = "Identify the total annual sales for each customer, categorized by sales type (store, catalog, or web), along with customer details such as name, preferred customer status, birth country, login, and email address."

Q5_CTE_TEXT = "What is the combined financial impact of sales and returns for each website, including sales revenue, profit, return amounts, and net losses, over a given period?"

Q11_CTE_TEXT = "Identify the total annual sales for each customer, distinguishing between store and web sales, while also providing customer details such as name, preferred customer status, birth country, login, and email address."

Q33_subquery_TEXT = "How much total sales revenue was generated by each manufacturer of 'Books' in March 1999 across different sales channels (store, catalog, and web) for customers located in the GMT-5 timezone?"
Q54_subquery_TEXT = "How can we combine and analyze sales data from both catalog and web channels to understand customer purchasing behavior and item sales performance across different sales platforms?"
Q71_subquery_TEXT = "How much revenue was generated from sales across web, catalog, and store channels in November 2001?"

Q60_subquery_TEXT = "How much total sales revenue was generated from jewelry items sold through store, catalog, and web channels in August 1999, specifically from customers located in the GMT-6 time zone?"
tpcds_q7 = "Compute the average quantity, list price, discount, and sales price for promotional items sold in stores where the " \
           "promotion is not offered by mail or a special event. Restrict the results to a specific gender, marital and " \
           "educational status."

tpcds_q1 = "Find customers who have returned items more than 20% more often than the average customer returns for " \
           "store in a given state for a given year."

tpcds_q2 = "Report the ratios of weekly web and catalog sales increases from one year to the next year for each week. That is, compute the increase of Monday, Tuesday, ... Sunday sales from one year to the following."

tpcds_q4 = "Find customers who spend more money via catalog than in stores. " \
           "Identify preferred customers and their " \
           "country of origin."